#!/usr/bin/env sh

browser="chromium-browser --kiosk"
wm="matchbox-window-manager"
url_file="$HOME/.config/rpi_wall/url"

$wm $
xset s off
xset -dpms
xset s noblank

echo "waiting for server"
while [ ! -f $url_file ]
do
    sleep 2
done

url=`cat $url_file`
$browser $url
